---
kind: Job
apiVersion: batch/v1
metadata:
  namespace: osm
  name: kube-osm-importer
template:
    metadata:
      name: kube-osm-importeer
    spec:
      containers:
      - name: importer
        image: anmoel/kube-osm-importer
        env:
        - name: PG_HOST
          value: "pgset-primary"
        - name: PG_PORT
          valueFrom:
            configMapKeyRef:
              name: osmconfig
              key: pg_port
          value: '5432'
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: osm-secret
              key: pg_username
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: osm-secret
              key: pg_password
        - name: PG_DATABASE
          valueFrom:
            configMapKeyRef:
              name: osmconfig
              key: pg_database
      restartPolicy: Never