---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgset-sa
  namespace: osm

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pgset-sa
  namespace: osm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:admin
subjects:
- kind: ServiceAccount
  name: pgset-sa
  namespace: osm


---

apiVersion: v1
kind: Service
metadata:
  name: pgset
  namespace: osm
  labels:
    app: pgset
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: pgset

---

kind: Service
apiVersion: v1
metadata:
  name: pgset-primary
  namespace: osm
  labels:
    name: pgset-primary
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 0
  selector:
    name: pgset-primary
  type: ClusterIP
  sessionAffinity: None

---

kind: Service
apiVersion: v1
metadata:
  name: pgset-replica
  namespace: osm
  labels:
    name: pgset-replica
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 0
  selector:
    name: pgset-replica
  type: ClusterIP
  sessionAffinity: None

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: pgset
  namespace: osm
spec:
  serviceName: pgset
  replicas: 2
  template:
    metadata:
      labels:
        app: pgset
    spec:
      containers:
      - name: pgset
        image: anmoel/kube-osm-pg
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: PG_PRIMARY_USER
          value: primaryuser
        - name: PGHOST
          value: "/tmp"
        - name: PG_MODE
          value: set
        - name: PG_PRIMARY_HOST
          value: pgset-primary
        - name: PG_PRIMARY_PORT
          valueFrom:
            configMapKeyRef:
              name: osmconfig
              key: pg_port
        - name: PG_PRIMARY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: osm-secret
              key: pg_primary_password
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: osm-secret
              key: pg_username
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: osm-secret
              key: pg_password
        - name: PG_DATABASE
          valueFrom:
            configMapKeyRef:
              name: osmconfig
              key: pg_database
        - name: PG_ROOT_PASSWORD
          value: password
        volumeMounts:
        - name: pgdata
          mountPath: "/pgdata"
          readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
